# Model Configuration for Multi-agent Risk Reporter
# Based on AGENTS.md specification

# Primary model for agents (generative tasks)
primary_model:
  provider: openai
  chat_model: "gpt-5-mini"
  temperature: 0.7
  max_output_tokens: 50000

# Alternative model option (if available)
alternative_model:
  provider: openai
  chat_model: "gpt-5"
  temperature: 0.7
  max_output_tokens: 50000

# Embedding model (separate from generative models)
embedding_model:
  model_name: "Qwen/Qwen3-Embedding-0.6B"

# Model selection for different agent types
agent_models:
  analyzer: "primary_model"    # Risk classification - needs precision
  verifier: "primary_model"    # Evidence validation - needs reasoning
  composer: "alternative_model" # Report generation - can use more capable model


