retrieval:
  top_k: 10
  prefilter_keywords: ["blocker","risk","delayed","waiting","asap","urgent","deadline","unresolved","issue"]

flags:
  uhpai:
    aging_days: 5
    role_weights: {"director": 2.0, "pm": 1.5, "ba": 1.2, "dev": 1.0}
  erb:
    critical_terms: ["blocked","waiting on","missing","unclear","cannot","security","payment","prod"]

scoring:
  repeat_weight: 0.5
  topic_weight: 0.7
  age_weight: 0.8
  role_weight: 1.0

chunking:
  chunk_size: 1000
  overlap: 100

report:
  top_n_per_project: 5
