name: CI
permissions: {contents: read}

concurrency:
  group: "ci-${{ github.ref }}"
  cancel-in-progress: true

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
 # workflow_dispatch: # for manual triggering until we have a proper trigger

env:
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  PYTHONUNBUFFERED: "1"
  # Provide a dummy key so imports/initialization that read the var won't fail.
  OPENAI_API_KEY: "sk-ci-placeholder"
  OPENAI_BASE_URL: "http://localhost"

jobs:
  lint:
    name: Lint & Quality Checks
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@v1
        with:
          version: "latest"

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('pyproject.toml', 'uv.lock') }}
          restore-keys: |
            venv-${{ runner.os }}-

      - name: Install lint tools
        run: |
          uv sync --dev

      - name: Black (repo)
        run: uv run black --check . --line-length=100

      - name: Ruff (repo)
        run: uv run ruff check . --fix

      - name: Mypy (optional on src/)
        run: |
          if [ -d src ]; then uv run mypy src/ --explicit-package-bases || true; else echo "no src/ dir, skipping mypy"; fi

      - name: Bandit (optional on src/)
        run: |
          if [ -d src ]; then uv run bandit -r src/ --format json --output bandit-report.json || true; else echo "no src/ dir, skipping bandit"; fi

      - name: Markdownlint (docs & README)
        run: |
          if [ -d docs ]; then markdownlint "**/*.md" || true; else echo "no docs/ dir"; fi
          if [ -f README.md ]; then markdownlint "README.md" || true; fi

  install-and-smoke:
    name: Install deps & smoke tests
    runs-on: ubuntu-latest
    needs: lint
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@v1
        with:
          version: "latest"

      - name: Install project (editable)
        run: |
          uv sync --dev

      - name: Import smoke (no heavy deps)
        run: |
          uv run python - <<'PY'
          import importlib
          for m in ["src.agents.graph"]:
              importlib.import_module(m)
          print("Core imports OK")
          PY

      - name: Run unit tests (if present)
        run: |
          if [ -d tests ]; then uv run pytest -q -ra --strict-markers --strict-config; else echo "No tests/ directory"; fi

      - name: Run CI smoke test
        run: |
          if [ -f tests/ci_smoke.py ]; then uv run tests/ci_smoke.py; else echo "No ci_smoke.py"; fi