name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
 # workflow_dispatch: # for manual triggering until we have a proper trigger

env:
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  PYTHONUNBUFFERED: "1"
  # Provide a dummy key so imports/initialization that read the var won't fail.
  OPENAI_API_KEY: "sk-ci-placeholder"

jobs:
  lint:
    name: Lint & Quality Checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@v1
        with:
          version: "latest"

      - name: Install lint tools
        run: |
          uv sync --extra dev --extra test

      - name: Black (repo)
        run: uv run black --check . --line-length=100

      - name: Ruff (repo)
        run: uv run ruff check .

      - name: Mypy (optional on src/)
        run: |
          if [ -d src ]; then uv run mypy src/ || true; else echo "no src/ dir, skipping mypy"; fi

      - name: Bandit (optional on src/)
        run: |
          if [ -d src ]; then uv run bandit -r src/ || true; else echo "no src/ dir, skipping bandit"; fi

      - name: Markdownlint (docs & README)
        run: |
          if [ -d docs ]; then markdownlint "**/*.md" || true; else echo "no docs/ dir"; fi
          if [ -f README.md ]; then markdownlint "README.md" || true; fi

  install-and-smoke:
    name: Install deps & smoke tests
    runs-on: ubuntu-latest
    needs: lint
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@v1
        with:
          version: "latest"

      - name: Install project (editable)
        run: |
          uv sync --extra dev --extra test

      - name: Import smoke (no heavy deps)
        run: |
          uv run python - <<'PY'
          import importlib
          for m in ["langgraph", "langchain", "chromadb", "openai"]:
              importlib.import_module(m)
          print("Core imports OK")
          PY

      - name: Run unit tests (if present)
        run: |
          if [ -d tests ]; then uv run pytest -q; else echo "No tests/ directory"; fi